config/routes.rb
Rails.application.routes.draw do
  root to: "application#index"

  get 'gameplay/new', as: 'new_game'
  post 'gameplay/parse_json', as: 'parse_json'
  get 'gameplay/play', as: 'play'
  get 'gameplay/submit_answer/:answer' => 'gameplay#submit_answer', as: 'submit_answer'
  get 'gameplay/game_over/:gameover_session' => 'gameplay#game_over', as: 'game_over'
  get 'gameplay/bank_money' => 'gameplay#bank_money', as: 'bank_money'

  get 'games' => 'games#index', as: 'highscores'
  get 'games/:id/questions' => 'games#game_questions', as: 'game_questions'

  get 'joker/fifty/:game_id' => 'joker#fifty_fifty', as: 'fifty_fifty'
  get 'joker/audience/:game_id' => 'joker#audience', as: 'audience'

  get 'about' => 'about#index', as: 'about'
end

app/models/game.rb
require 'net/http'

class Game < ActiveRecord::Base
  def self.winnings_table
    {0 => [50, 0],
     1 =>  [100, 0],
     2 =>  [200, 0],
     3 =>  [300, 0],
     4 =>  [500, 500],
     5 =>  [1000, 500],
     6 =>  [2000, 500],
     7 =>  [4000, 500],
     8 =>  [8000, 500],
     9 =>  [16000, 16000],
     10 =>  [32000, 16000],
     11 =>  [64000, 16000],
     12 =>  [125000, 16000],
     13 =>  [500000, 16000],
     14 =>  [1000000, 16000],
    }

  end

  validates :session_id, :current_level, presence: true
  validates :current_level, numericality: { only_integer: true}
  has_many :questions, dependent: :destroy

  def self.check_file_validity(address)
    begin
      url = URI.parse(address)
      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = (url.scheme == "https")
      response = http.request_head(url.path)
      size = Integer(response['content-length'])
      if size > 1024 * 1024 * 3
        return false
      end
    rescue URI::InvalidURIError, SocketError
      return false
    end
    return true
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    #Display highest scoring games first.
    @games = Game.all.where(running: false).order(cash_won: :desc)
  end

  def game_questions
    #Display all answered questions for a particular game.
    game_id = params[:id]
    @questions = Game.find(game_id).questions.where.not(answered: -1)
  end

end

app/views/games/game_questions.html.erb
<table class="games-table">
  <tr>
    <th>Level</th>
    <th>Question</th>
    <th>Your Answer</th>
  <% @questions.each do |question| %>
    <tr <%=  question.solution == question.answered ?
 'bgcolor=#9eef7a' : 'bgcolor=#ff6161'%>  >
    <td align='left'><%= question.level %></td>
    <td align='right'><%= question.text %></td>
    <% given_answer = question.attributes["answer" + question.answered.to_s] %>
    <td align='right'><%= given_answer %></td>
  </tr>
<% end %>
</table>

<%= link_to "Go back", highscores_path %>

app/views/games/index.html.erb
<table class="games-table">
  <tr>
    <th>Date completed</th>
    <th>Amount won</th>
    <th></th>
  <% @games.each do |game| %>
    <tr>
    <td><%= game.updated_at %></td>
    <td align='right'><%= number_to_currency(game.cash_won) %></td>
    <td align='right'><%= link_to 'show questions', game_questions_path(game.id) %>
  </tr>
<% end %>
</table>