config/routes.rb
Rails.application.routes.draw do
  root to: "application#index"

  get 'gameplay/new', as: 'new_game'
  post 'gameplay/parse_json', as: 'parse_json'
  get 'gameplay/play', as: 'play'
  get 'gameplay/submit_answer/:answer' => 'gameplay#submit_answer', as: 'submit_answer'
  get 'gameplay/game_over/:gameover_session' => 'gameplay#game_over', as: 'game_over'
  get 'gameplay/bank_money' => 'gameplay#bank_money', as: 'bank_money'

  get 'games' => 'games#index', as: 'highscores'
  get 'games/:id/questions' => 'games#game_questions', as: 'game_questions'

  get 'joker/fifty/:game_id' => 'joker#fifty_fifty', as: 'fifty_fifty'
  get 'joker/audience/:game_id' => 'joker#audience', as: 'audience'

  get 'about' => 'about#index', as: 'about'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @game = Game.where(session_id: session.id).where(running: true).order(created_at: :desc).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type.to_s
    when "success"
      "alert-success"
    when "error"
      "alert-danger"
    when "alert"
      "alert-warning"
    when "notice"
      "alert-info"
    else
      flash_type.to_s
    end
  end
end

app/views/application/index.html.erb
<a class="btn btn-default" href="<%= new_game_path %>" role="button">
  <span class="glyphicon glyphicon-play-circle"></span>
  Start New Game
</a>
<a class="btn btn-default" href="<%= play_path %>"
  role="button" <%= 'disabled="disabled"' if @game == nil %>>
  <span class="glyphicon glyphicon-share-alt"></span>
  Continue existing Game
</a>