config/routes.rb
Rails.application.routes.draw do
  root to: "application#index"

  get 'gameplay/new', as: 'new_game'
  post 'gameplay/parse_json', as: 'parse_json'
  get 'gameplay/play', as: 'play'
  get 'gameplay/submit_answer/:answer' => 'gameplay#submit_answer', as: 'submit_answer'
  get 'gameplay/game_over/:gameover_session' => 'gameplay#game_over', as: 'game_over'
  get 'gameplay/bank_money' => 'gameplay#bank_money', as: 'bank_money'

  get 'games' => 'games#index', as: 'highscores'
  get 'games/:id/questions' => 'games#game_questions', as: 'game_questions'

  get 'joker/fifty/:game_id' => 'joker#fifty_fifty', as: 'fifty_fifty'
  get 'joker/audience/:game_id' => 'joker#audience', as: 'audience'

  get 'about' => 'about#index', as: 'about'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Wwm</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Millionaire</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li <%= 'class=active' if params[:controller] == 'gameplay' %>><a href="<%= play_path %>">Play</a></li>
        <li <%= 'class=active' if params[:controller] == 'games' %>><a href="<%= highscores_path %>">Stats</a></li>
        <li <%= 'class=active' if params[:controller] == 'about' %>> <a href="<%= about_path %>">About</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<div class="container">
  <div id="flash-wrapper">
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %>" id="flashbox">
    <%= message %>
  </div>
<% end %>
  </div>

  <%= yield %>

</div><!-- /.container -->


<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</body>
</html>